name: Tambah Berita TXT & Gambar

on:
  workflow_dispatch:
    inputs:
      judul:
        description: "Judul berita (tanpa spasi untuk nama folder)"
        required: true
      isi:
        description: "Isi lengkap berita"
        required: true

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Simpan berita dan gambar placeholder
        run: |
          nama="${{ github.event.inputs.judul }}"

          # Buat folder berita/nama_berita
          mkdir -p "berita/$nama"

          # Simpan teks berita
          echo "${{ github.event.inputs.isi }}" > "berita/$nama/text.txt"

          # Buat placeholder gambar (supaya selalu ada file picture.png)
          echo "Ganti file ini dengan gambar asli" > "berita/$nama/picture.png"

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add "berita/$nama/text.txt" "berita/$nama/picture.png"
          git commit -m "Tambah berita: $nama"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.berita }}
